// src/App.vue
<template>
  <h1 class="underline underline-offset-5 underline-blue-600">
    .projectrc
  </h1>

  <p>
    Since you are here, you are probably wondering why and what this <span
      class="underline underline-offset-5 underline-blue-700"
    >.projectrc</span> is.
  </p>

  <p>
    Well, it's a file that are used by <a
      href="https://github.com/luxass/luxass.dev/blob/main/scripts/update-site.ts"
      target="_blank" rel="noopener noreferrer"
    >my website</a> to generate a list of projects that are being showed <a
      href="https://luxass.dev/projects" target="_blank" rel="noopener noreferrer"
    >here</a>.
  </p>
</template>

<style>
html {
  @apply antialiased touch-manipulation scroll-smooth text-base;
  text-rendering: optimizeLegibility;
}

body {
  @apply text-neutral-300 bg-neutral-900 py-8 min-h-screen max-w-2xl md:!mx-auto !mx-4 font-sans flex flex-col justify-between min-h-100dvh;
}

p {
  @apply line-height-relaxed;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  @apply text-neutral-100 font-semibold my-8;
}

h1 {
  @apply text-2xl;
}

h2 {
  @apply text-xl;
}

h3 {
  @apply text-lg;
}

h4 {
  @apply text-base;
}

h5 {
  @apply text-sm;
}

h6 {
  @apply text-xs;
}

strong {
  @apply font-medium text-neutral-100;
}

img {
  @apply mx-auto rounded my-6;
}
</style>

// app/page.tsx
import { codeToHtml } from "shikiji";
import { toJSONSchema } from "@gcornut/valibot-json-schema";
import Link from "next/link";
import { SCHEMA } from "~/lib/schema";
import { CopyButton } from "~/components/CopyButton";

export default async function Home() {
  const jsonSchema = toJSONSchema({
    schema: SCHEMA,
  });
  const html = await codeToHtml(JSON.stringify(jsonSchema, null, 2), {
    lang: "json",
    themes: {
      light: "vitesse-light",
      dark: "vitesse-dark",
    },
  });

  return (
    <>
      <h1 className="mb-8 text-3xl font-semibold">.projectrc</h1>

      <article>
        <p>
          Since you are here, you are probably wondering why and what this
          {" "}
          <span className="rounded bg-gray-200 p-0.5 dark:bg-gray-400/10">.projectrc</span>
          {" "}
          is.
        </p>
        <p>
          Well, it&apos;s a file that are used by
          {" "}
          <Link href="https://luxass.dev" className="rounded bg-gray-200 p-0.5 dark:bg-gray-400/10">
            <code>my website</code>
          </Link>
          {" "}
          to generate a list of projects thare are being shown
          {" "}
          <Link className="rounded bg-gray-200 p-0.5 dark:bg-gray-400/10" href="https://luxass.dev/projects">here</Link>
          .
        </p>

      </article>

      <div className="my-4">

        <h2 className="my-2 text-xl font-semibold">
          You can see the schema used here.
        </h2>

        <div className="group relative">
          <div
            dangerouslySetInnerHTML={{
              __html: html,
            }}
          />
          <CopyButton text={JSON.stringify(jsonSchema, null, 2)} />
        </div>
      </div>
    </>
  );
}
